### ISSUE TITLE
Error while closing the stream reader when is over GZipStream

### ISSUE THREAD

**Issue by prakash122** [dotMorten/SharpGIS.GZipWebClient#1]
I am using a stream reader over GZipStream. And trying to read line.

```
                        var streamReadr = new StreamReader(new GZipStream(streamResponse));

                        string ch;
                        var responseStr = "";
                        while ((ch=streamReadr.ReadLine()) !=null)
                        {
                            responseStr += ch;
                        }
                        streamReadr.Close();
                        streamResponse.Close();
                        webResponse.Close();
```

I am getting an error while closing StreamReader instance, very very rarely.

"Protocol error. AvailableBytesIn=5, expected 8"
in file : ZLibStream.cs on the line
In  function:"finish()" 

values were :
InpuBuffer size 8192 bytes
NextIn value is 8187
trailer is of 8 bytes

I didnot understand why this case has come.
Does this mean CRC check has failed. 
But it is happening for only a certain parameters to the same api. From the earlier code I am able retrieve the complete responseStr but getting an error in finish.
It is working normally for other platforms with different libraries.
I am looking into this but want to report to you.
I am not sure if this is an issue or not.

**Comment by dotMorten** [comment]
I've seen this bug on and off (<1%). Do you have an endpoint/resource/stream that consistently returns this error? That would help a lot towards tracking down this issue.

**Comment by prakash122** [comment]
I can see that the error comes only on certain kind of input which is <1% possible. Tell me how I can help in this case.  I haven't tried debugging whole of the code, since I am struck with some other issue. Currently, I am catching with an empty catch block.

**Comment by dotMorten** [comment]
Please try again with the latest changes. The client is using a complete different approach to decode the gzip stream now, and therefore this is likely not an issue any longer.
