### ISSUE TITLE
NuGet package not up to date

### ISSUE THREAD

**Issue by ovatsus** [dotMorten/SharpGIS.GZipWebClient#13]
If I use the published 1.4.0 nuget package, and set a UserAgent, that user agent is discarded and "Test" is sent instead. If I build from source, it works fine. Could you please check if the nuget package has the right code?

**Comment by ovatsus** [comment]
Actually, it's not a problem with the package, when building from source, sometimes you get the right user agent, sometimes you get "Test". Seems completely random, can't figure out the pattern :(

**Comment by dotMorten** [comment]
I've discontinued maintenance of this project now that Microsoft finally provides an HttpClient NuGet package that supports compression: https://www.nuget.org/packages/Microsoft.Net.Http
