### ISSUE TITLE
WebExceptions are not properly handled

### ISSUE THREAD

**Issue by aleksk** [dotMorten/SharpGIS.GZipWebClient#5]
If WebClient returns an error, NPE will be thrown, because the WebException is not properly handled.

The GZipWebClient::GetWebResponse method should look like this:
protected override WebResponse GetWebResponse(WebRequest request, IAsyncResult result)
{
    WebResponse response;
    try
    {
        response = base.GetWebResponse(request, result);
    }
    catch (WebException we)
    {
        response = we.Response;
    }
    catch
    {
        response = null;
    }

```
return response != null
            ? (response.Headers[HttpRequestHeader.ContentEncoding] == "gzip"
                    ? new GZipWebResponse(response)
                    : response)
            : null;
```

}

**Comment by dotMorten** [comment]
This is not correct. If the underlying webrequest fails, the error should not be trapped and swallowed, but bubbled up to the calling method. Without that, there's no way to detect that the webrequest failed.

**Comment by aleksk** [comment]
The code above is a suggestion, but the issue exists.

The current implementation doesn't throw anything:
catch { return null; }

Fix is up to you since you're an owner.

**Comment by dotMorten** [comment]
I'm not saying there isn't a scenario where an exception could be thrown. What I'm saying is that its OK that the exception is being thrown.
It's up to the client that uses this class to handle these exceptions. Throwing an exception in a library isn't necessarily a bug. However throwing an exception in an application is. This library is not an application though.

**Comment by aleksk** [comment]
You _don't_ throw anything from the code.

**Comment by aleksk** [comment]
And let's not talk about exceptions vs error codes behavior. You designed this class to be a replacement for the WebClient. WebClient throws WebException, your implementation doesn't.
