### ISSUE TITLE
Encoding request streams

### ISSUE THREAD

**Issue by staticfloat** [dotMorten/SharpGIS.GZipWebClient#7]
Hey there, this is a great help for downloading large amounts of data; I've looked through the source and I don't see any way of encoding large amounts of data to, for example, POST to a webservice.  Is there any such functionality available?  And if there isn't, is there a simple way to work this kind of functionality into your framework?

**Comment by dotMorten** [comment]
There's nothing in the http specification that describes compressing request data, so no this is not planned. Secondly there isn't any API in phone that allows compression (only decompression)

**Comment by dotMorten** [comment]
...jut wanted to add there's nothing wrong with uploading for instance a zip file, but the server would need to define that what you're sending it must be a zip file.  In other words it would be a service definition for that specific service.
